### ISSUE TITLE
arillo:flow-router-helpers

### ISSUE THREAD

**Issue by valorloff** [VeliovGroup/flow-router#7]
Hi!
After adding arillo:flow-router-helpers, 
`Exception in template helper: ReferenceError: FlowRouter is not defined,`
in /lib/ directory present:
`Package['kadira:flow-router'] = Package['ostrio:flow-router-extra'];`
is it compatible packages?

**Comment by dr-dimitru** [comment]
Hello @valorloff ,

Since v3.0 `FlowRouter` is not exported to global namespace.
And that means `arillo:flow-router-helpers` wouldn't work.

Good news - I made [this snippet](https://gist.github.com/dr-dimitru/cce12c1ee34fc6ff0c8be66142bc86ff) which brings it back.
Let me know if it fits your needs.

Probably we should send a PR to `zimme:active-route` and `arillo:flow-router-helpers`

Would like to know thoughts of @arillo and @zimme , will you accept a PR?

**Comment by zimme** [comment]
@dr-dimitru, Just a note on my package. I've created [activeroute:core](/meteor-activeroute/core), [activeroute:flow-router](/meteor-activeroute/flow-router) and [activeroute:blaze](/meteor-activeroute/blaze) which works a bit different and that's where I'll be putting my focus and handing it over to the community if there are people willing to help out with maintaining.

**Comment by dr-dimitru** [comment]
Hello @zimme ,

Got it. Quick guess - there is no possibility even for weak dependency for `ostrio:flow-router-extra` in `zimme:active-route`, right?

**Comment by zimme** [comment]
We could probably update that package to have a weak dependency but if it doesn't export `FlowRouter` I don't believe it will work. Open an issue and write down some specifics on what's needed from my package to make this work and I'll see if I have time to do it my self otherwise I'm happy to accept a PR if that will help people out.

**Comment by valorloff** [comment]
I did it this way:
`meteor remove arillo:flow-router-helpers`
and
`import '/imports/modules/active-route.js';`
and pathFor works!
and please explain, what is export { ActiveRoute, FlowRouterHelpers } for?
for server purposes only?

**Comment by dr-dimitru** [comment]
`{ ActiveRoute, FlowRouterHelpers }` this variables is exported for case if for any reason you want to use its methods directly in JS code.

**Comment by valorloff** [comment]
Thanks for super fast response and support!

**Comment by dr-dimitru** [comment]
@valorloff you're welcome :)

Thank you for reasonable question, will add this snippet to the docs.

**Comment by valorloff** [comment]
I suggest include FR-helpers in FR-extra package out of the box

**Comment by dr-dimitru** [comment]
@valorloff 

> I suggest include FR-helpers in FR-extra package out of the box

Sounds reasonable, will schedule this for next release.

**Comment by dr-dimitru** [comment]
Hello @valorloff ,

Implemented in [v3.1.0](https://github.com/VeliovGroup/flow-router/releases/tag/3.1.0)

Let me know how it works on your end.
Thank you for feature suggestion

**Comment by valorloff** [comment]
Great news!
Here it is promptness!

**Comment by dr-dimitru** [comment]
@valorloff ,

Thank you once again.
Have you tested it on your end?

**Comment by valorloff** [comment]
That's just update FR-extra to 3.1.0 and remove import of active-route.js, 
pathFor and urlFor works! nice!
@dr-dimitru, big thanks for your support!
Can anybody else check FlowRouter-extra helpers in their project ?

**Comment by dr-dimitru** [comment]
@valorloff we are actively using FR-Extra in our projects.
It works on our end.

I'm assuming we can close this one now

**Comment by valorloff** [comment]
Beyond any doubt!

**Comment by dr-dimitru** [comment]
Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/flow-router)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/flow-router-extra)
